/**
 * Copies the compiled ABIs out of artifacts/ into lib/contracts/abis.ts.
 *
 * The generated file is committed so the app and the indexer type-check
 * without needing a Hardhat compile first, and `as const` gives viem/wagmi
 * full argument inference. Re-run after changing any contract:
 *   npm run contracts:abis
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const CONTRACTS = [
  { file: "ClassroomToken", exportName: "classroomTokenAbi" },
  { file: "ClassBadges", exportName: "classBadgesAbi" },
  { file: "ClassroomFactory", exportName: "classroomFactoryAbi" },
] as const;

function readAbi(contract: string): unknown[] {
  const path = join(
    root,
    "artifacts",
    "contracts",
    `${contract}.sol`,
    `${contract}.json`,
  );
  const artifact = JSON.parse(readFileSync(path, "utf8")) as { abi: unknown[] };
  return artifact.abi;
}

const sections = CONTRACTS.map(({ file, exportName }) => {
  const abi = readAbi(file);
  return `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;`;
});

const output = `// AUTO-GENERATED by scripts/export-abis.ts - do not edit by hand.
// Run \`npm run contracts:abis\` after changing any contract.

${sections.join("\n\n")}
`;

const outPath = join(root, "lib", "contracts", "abis.ts");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, output, "utf8");

console.log(`Wrote ${outPath}`);
for (const { file } of CONTRACTS) {
  console.log(`  - ${file}`);
}
